import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MouseGlow from "@/app/components/MouseGlow";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} antialiased `}>
      <body>
        <MouseGlow />
        {children}
      </body>
    </html>
  );
}
